import { ArrowUpRight, ClipboardList, Clock3, Package, Plus, Wrench } from 'lucide-react'
import { Link } from 'react-router'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { serviceRequests } from '@/features/service-requests/data'
import { ServiceRequestStatusBadge } from '@/features/service-requests/components/status-badge'

const kpis = [
  { label: 'Active requests', value: '18', detail: '+4 from yesterday', icon: ClipboardList, tone: 'text-primary' },
  { label: 'Awaiting inspection', value: '06', detail: '2 due today', icon: Clock3, tone: 'text-sky-600' },
  { label: 'Low-stock parts', value: '09', detail: '3 need ordering', icon: Package, tone: 'text-amber-600' },
  { label: 'Available mechanics', value: '07', detail: '12 total on roster', icon: Wrench, tone: 'text-emerald-600' },
]

export function DashboardPage() {
  return <div className="mx-auto max-w-[1440px] space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Wednesday, July 22, 2026</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Good evening, Harley</h1><p className="mt-1 text-sm text-muted-foreground">Here is the current operating picture for your shop.</p></div><Button asChild><Link to="/service-requests/new"><Plus />New request</Link></Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map((kpi) => { const Icon = kpi.icon; return <Card key={kpi.label}><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-muted-foreground">{kpi.label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{kpi.value}</p><p className="mt-1 text-xs text-muted-foreground">{kpi.detail}</p></div><div className={`rounded-md bg-muted p-2.5 ${kpi.tone}`}><Icon className="size-5" /></div></CardContent></Card> })}</div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,1fr)]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Active service requests</CardTitle><CardDescription>Jobs that need attention today.</CardDescription></div><Button variant="ghost" size="sm" asChild><Link to="/service-requests">View all<ArrowUpRight /></Link></Button></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Request</TableHead><TableHead>Vehicle</TableHead><TableHead>Mechanic</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{serviceRequests.slice(0, 4).map((request) => <TableRow key={request.id}><TableCell><Link className="font-medium text-primary hover:underline" to={`/service-requests/${request.id}`}>{request.id}</Link><p className="mt-0.5 text-xs text-muted-foreground">{request.customer}</p></TableCell><TableCell>{request.vehicle}</TableCell><TableCell className="text-muted-foreground">{request.mechanic}</TableCell><TableCell><ServiceRequestStatusBadge status={request.status} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Parts attention</CardTitle><CardDescription>Items approaching reorder levels.</CardDescription></CardHeader><CardContent className="space-y-4">{['Brake pad set', '10W-40 engine oil', 'Air filter element', 'Drive chain 428'].map((part, index) => <div key={part} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{part}</p><p className="text-xs text-muted-foreground">{index + 2} units remaining</p></div><Badge variant={index === 0 ? 'destructive' : 'warning'}>{index === 0 ? 'Critical' : 'Low'}</Badge></div>)}</CardContent></Card></div></div>
}
